# Generated by Django 4.1.2 on 2022-10-26 14:50

import albums.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/audios', validators=[albums.validators.audio_file_validator]),
        ),
    ]
