# Generated by Django 4.1.2 on 2022-10-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_num_admin_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='num_admin_approved',
            new_name='count_admin_approved',
        ),
    ]
