# Generated by Django 4.1.2 on 2022-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_rename_num_admin_approved_artist_count_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='count_admin_approved',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
